### ISSUE TITLE
remove spaces from committee field when it appears

### ISSUE THREAD

**Issue by jsfenfen** [sunlightlabs/read_FEC#127]
Somehow some spaces are getting through. This should be fixed ASAP. 

[2016-05-13 16:17:29,147: ERROR/MainProcess] Task celeryproj.tasks.process_filing_body_celery[8688057c-718a-4b26-9d12-f2e142cd1926] raised exception: DataError('value too long for type character varying(9)\nCONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"\n',)
Traceback (most recent call last):
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/projects/realtimefec/src/realtimefec/fecreader/celeryproj/tasks.py", line 96, in process_filing_body_celery
    process_filing_body(filingnum)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/filing_body_processor.py", line 147, in process_filing_body
    cd.commit_all()
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 90, in commit_all
    self._commit_rows(sked)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 56, in _commit_rows
    self.cursor.copy_from(self.writers[sked]['stringio'], dbname, sep='|', size=length, columns=self.fields[sked], null="")
DataError: value too long for type character varying(9)
CONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"

[2016-05-13 16:17:29,192: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F2 - 1051569
[2016-05-13 16:17:29,236: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F1 - 1051608
[2016-05-13 16:17:29,282: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F2 - 1051619
[2016-05-13 16:17:29,327: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F1 - 1051631
[2016-05-13 16:17:29,378: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F2 - 1051638
[2016-05-13 16:17:29,420: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F1 - 1051648
[2016-05-13 16:17:29,463: ERROR/PoolWorker-2467] process_filing_body: Not a parseable form: F2 - 1051659
[2016-05-13 16:17:29,569: ERROR/PoolWorker-2468] process_filing_body: Not a parseable form: F2 - 1051661

**Comment by jsfenfen** [comment]
So I can find three instances of this, always in the beneficiary committee field. 





3 17:12:24,884: ERROR/MainProcess] Task celeryproj.tasks.process_filing_body_celery[95f72649-8510-40ed-8bc7-307fad8ecd70] raised exception: DataError('value too long for type character varying(9)\nCONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"\n',)
Traceback (most recent call last):
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/projects/realtimefec/src/realtimefec/fecreader/celeryproj/tasks.py", line 96, in process_filing_body_celery
    process_filing_body(filingnum)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/filing_body_processor.py", line 147, in process_filing_body
    cd.commit_all()
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 90, in commit_all
    self._commit_rows(sked)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 56, in _commit_rows
    self.cursor.copy_from(self.writers[sked]['stringio'], dbname, sep='|', size=length, columns=self.fields[sked], null="")
DataError: value too long for type character varying(9)
CONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"




[2016-05-13 17:12:25,731: ERROR/MainProcess] Task celeryproj.tasks.process_filing_body_celery[12e0a965-b0f4-4954-87ba-ecbeee78caff] raised exception: DataError('value too long for type character varying(9)\nCONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"\n',)
Traceback (most recent call last):
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/projects/realtimefec/src/realtimefec/fecreader/celeryproj/tasks.py", line 96, in process_filing_body_celery
    process_filing_body(filingnum)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/filing_body_processor.py", line 147, in process_filing_body
    cd.commit_all()
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 90, in commit_all
    self._commit_rows(sked)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 56, in _commit_rows
    self.cursor.copy_from(self.writers[sked]['stringio'], dbname, sep='|', size=length, columns=self.fields[sked], null="")
DataError: value too long for type character varying(9)
CONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"

[2016-05-13 17:12:25,832: ERROR/MainProcess] Task celeryproj.tasks.process_filing_body_celery[d0acb2c7-4c8a-4f38-81c0-2ff4f8748935] raised exception: DataError('value too long for type character varying(9)\nCONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"\n',)
Traceback (most recent call last):
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/projects/realtimefec/src/realtimefec/fecreader/celeryproj/tasks.py", line 96, in process_filing_body_celery
    process_filing_body(filingnum)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/filing_body_processor.py", line 147, in process_filing_body
    cd.commit_all()
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 90, in commit_all
    self._commit_rows(sked)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 56, in _commit_rows
    self.cursor.copy_from(self.writers[sked]['stringio'], dbname, sep='|', size=length, columns=self.fields[sked], null="")




DataError: value too long for type character varying(9)
CONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"

[2016-05-13 17:12:25,987: ERROR/MainProcess] Task celeryproj.tasks.process_filing_body_celery[a216765c-b6c2-41ad-8863-6b12aecd006f] raised exception: DataError('value too long for type character varying(9)\nCONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"\n',)
Traceback (most recent call last):
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/projects/realtimefec/virt/local/lib/python2.7/site-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/projects/realtimefec/src/realtimefec/fecreader/celeryproj/tasks.py", line 96, in process_filing_body_celery
    process_filing_body(filingnum)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/filing_body_processor.py", line 147, in process_filing_body
    cd.commit_all()
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 90, in commit_all
    self._commit_rows(sked)
  File "/projects/realtimefec/src/realtimefec/fecreader/formdata/utils/write_csv_to_db.py", line 56, in _commit_rows
    self.cursor.copy_from(self.writers[sked]['stringio'], dbname, sep='|', size=length, columns=self.fields[sked], null="")
DataError: value too long for type character varying(9)
CONTEXT:  COPY formdata_skedb, line 11, column beneficiary_committee_fec_id: " C00605642"
